export const data = [
    {
        "flow": "Invoer nationaal",
        "Consumptie huishoudens": 91,
        "Consumptie huishoudensColor": "hsla(205, 40%, 79%, 1)",
        "Dienstverlening bedrijven": 113,
        "Dienstverlening bedrijvenColor": "hsla(83, 47%, 73%, 1)",
        "Investeringen vaste activa": 20,
        "Investeringen vaste activaColor": "hsla(4, 55%, 75%, 1)",
        "Overheid": 170,
        "OverheidColor": "hsla(35, 74%, 73%, 1)",
        "Productie goederen": 152,
        "Productie goederenColor": "hsla(269, 24%, 77%, 1)",
        "Verandering voorraden": 95,
        "Verandering voorradenColor": "hsla(26, 74%, 58%, 1)"
    },
    {
        "flow": "Invoer internationaal",
        "Consumptie huishoudens": 19,
        "Consumptie huishoudensColor": "hsla(205, 40%, 79%, 1)",
        "Dienstverlening bedrijven": 31,
        "Dienstverlening bedrijvenColor": "hsla(83, 47%, 73%, 1)",
        "Investeringen vaste activa": 200,
        "Investeringen vaste activaColor": "hsla(4, 55%, 75%, 1)",
        "Overheid": 17,
        "OverheidColor": "hsla(35, 74%, 73%, 1)",
        "Productie goederen": 52,
        "Productie goederenColor": "hsla(269, 24%, 77%, 1)",
        "Verandering voorraden": 59,
        "Verandering voorradenColor": "hsla(26, 74%, 58%, 1)"
    },
    {
        "flow": "Aanbod eigen regio",
        "Consumptie huishoudens": 61,
        "Consumptie huishoudensColor": "hsla(205, 40%, 79%, 1)",
        "Dienstverlening bedrijven": 83,
        "Dienstverlening bedrijvenColor": "hsla(83, 47%, 73%, 1)",
        "Investeringen vaste activa": 230,
        "Investeringen vaste activaColor": "hsla(4, 55%, 75%, 1)",
        "Overheid": 71,
        "OverheidColor": "hsla(35, 74%, 73%, 1)",
        "Productie goederen": 25,
        "Productie goederenColor": "hsla(269, 24%, 77%, 1)",
        "Verandering voorraden": 99,
        "Verandering voorradenColor": "hsla(26, 74%, 58%, 1)"
    },
]