export const data = [
    {
        "id": "Chemische basisproducten",
        "worth": 4000,
        "data": [
            {"x": "Dysprosium", "y": 12},
            {"x": "Neodymium", "y": 38},
            {"x": "Terbium", "y": 20},
            {"x": "Magnesium", "y": 67},
            {"x": "Niobrum", "y": 50},
            {"x": "Samarium", "y": 60},
            {"x": "Iridium", "y": 100},
            {"x": "Praseodymium", "y": 79},
            {"x": "Ruthenium", "y": 10},
            {"x": "Rhodium", "y": 50},
            {"x": "Cerium", "y": 84},
            {"x": "Kobalt", "y": 52},
            {"x": "Europium", "y": 100},
            {"x": "Ytterbium", "y": 26},
            {"x": "Strontium", "y": 61},
            {"x": "Fosfor", "y": 80},
            {"x": "Platina", "y": 10},
            {"x": "Gallium", "y": 39},
            {"x": "Boor", "y": 26},
            {"x": "Palladium", "y": 94},
            {"x": "Gadolinium", "y": 94},
            {"x": "Wolfraam", "y": 64},
            {"x": "Yttrium", "y": 49},
            {"x": "Lanthanum", "y": 45},
            {"x": "Anitmoon", "y": 93},
            {"x": "Beryllium", "y": 44},
            {"x": "Vanadium", "y": 18},
            {"x": "Scandium", "y": 44},
            {"x": "Mangaan", "y": 35},
            {"x": "Lithium", "y": 32},
            {"x": "Aluminium", "y": 37},
            {"x": "Garmanium", "y": 42},
            {"x": "Silicium", "y": 37},
            {"x": "Tantalum", "y": 8},
            {"x": "Grafiet", "y": 50},
            {"x": "Veldsplaat", "y": 96},
            {"x": "Barieten", "y": 37},
            {"x": "Fluoriet", "y": 14},
            {"x": "Cokeskolen", "y": 56}
        ]
    },
    {
        "id": "Producten van de auto-industrie",
        "worth": 2200,
        "data": [
            {"x": "Dysprosium", "y": 43},
            {"x": "Neodymium", "y": 76},
            {"x": "Terbium", "y": 25},
            {"x": "Magnesium", "y": 58},
            {"x": "Niobrum", "y": 92},
            {"x": "Samarium", "y": 12},
            {"x": "Iridium", "y": 6},
            {"x": "Praseodymium", "y": 83},
            {"x": "Ruthenium", "y": 17},
            {"x": "Rhodium", "y": 63},
            {"x": "Cerium", "y": 24},
            {"x": "Kobalt", "y": 31},
            {"x": "Europium", "y": 78},
            {"x": "Ytterbium", "y": 69},
            {"x": "Strontium", "y": 44},
            {"x": "Fosfor", "y": 91},
            {"x": "Platina", "y": 10},
            {"x": "Gallium", "y": 52},
            {"x": "Boor", "y": 73},
            {"x": "Palladium", "y": 39},
            {"x": "Gadolinium", "y": 89},
            {"x": "Wolfraam", "y": 64},
            {"x": "Yttrium", "y": 15},
            {"x": "Lanthanum", "y": 40},
            {"x": "Anitmoon", "y": 96},
            {"x": "Beryllium", "y": 34},
            {"x": "Vanadium", "y": 81},
            {"x": "Scandium", "y": 24},
            {"x": "Mangaan", "y": 55},
            {"x": "Lithium", "y": 66},
            {"x": "Aluminium", "y": 10},
            {"x": "Garmanium", "y": 74},
            {"x": "Silicium", "y": 25},
            {"x": "Tantalum", "y": 56},
            {"x": "Grafiet", "y": 13},
            {"x": "Veldsplaat", "y": 98},
            {"x": "Barieten", "y": 67},
            {"x": "Fluoriet", "y": 31},
            {"x": "Cokeskolen", "y": 59}
        ]
    },
    {
        "id": "Overige voedingsmiddelen en tabaksproducten",
        "worth": 2000,
        "data": [
            {"x": "Dysprosium", "y": 27},
            {"x": "Neodymium", "y": 54},
            {"x": "Terbium", "y": 36},
            {"x": "Magnesium", "y": 70},
            {"x": "Niobrum", "y": 89},
            {"x": "Samarium", "y": 16},
            {"x": "Iridium", "y": 95},
            {"x": "Praseodymium", "y": 41},
            {"x": "Ruthenium", "y": 22},
            {"x": "Rhodium", "y": 67},
            {"x": "Cerium", "y": 74},
            {"x": "Kobalt", "y": 38},
            {"x": "Europium", "y": 47},
            {"x": "Ytterbium", "y": 12},
            {"x": "Strontium", "y": 84},
            {"x": "Fosfor", "y": 39},
            {"x": "Platina", "y": 50},
            {"x": "Gallium", "y": 33},
            {"x": "Boor", "y": 88},
            {"x": "Palladium", "y": 44},
            {"x": "Gadolinium", "y": 67},
            {"x": "Wolfraam", "y": 13},
            {"x": "Yttrium", "y": 92},
            {"x": "Lanthanum", "y": 18},
            {"x": "Anitmoon", "y": 56},
            {"x": "Beryllium", "y": 29},
            {"x": "Vanadium", "y": 73},
            {"x": "Scandium", "y": 60},
            {"x": "Mangaan", "y": 22},
            {"x": "Lithium", "y": 45},
            {"x": "Aluminium", "y": 90},
            {"x": "Garmanium", "y": 38},
            {"x": "Silicium", "y": 12},
            {"x": "Tantalum", "y": 79},
            {"x": "Grafiet", "y": 62},
            {"x": "Veldsplaat", "y": 94},
            {"x": "Barieten", "y": 77},
            {"x": "Fluoriet", "y": 41},
            {"x": "Cokeskolen", "y": 19}
        ]
    },
    {
        "id": "Farmaceutische producten en chemische specialiteiten",
        "worth": 1905,
        "data": [
            {"x": "Dysprosium", "y": 39},
            {"x": "Neodymium", "y": 59},
            {"x": "Terbium", "y": 80},
            {"x": "Magnesium", "y": 45},
            {"x": "Niobrum", "y": 73},
            {"x": "Samarium", "y": 92},
            {"x": "Iridium", "y": 8},
            {"x": "Praseodymium", "y": 56},
            {"x": "Ruthenium", "y": 22},
            {"x": "Rhodium", "y": 71},
            {"x": "Cerium", "y": 33},
            {"x": "Kobalt", "y": 44},
            {"x": "Europium", "y": 17},
            {"x": "Ytterbium", "y": 77},
            {"x": "Strontium", "y": 29},
            {"x": "Fosfor", "y": 67},
            {"x": "Platina", "y": 4},
            {"x": "Gallium", "y": 64},
            {"x": "Boor", "y": 89},
            {"x": "Palladium", "y": 42},
            {"x": "Gadolinium", "y": 99},
            {"x": "Wolfraam", "y": 32},
            {"x": "Yttrium", "y": 66},
            {"x": "Lanthanum", "y": 58},
            {"x": "Anitmoon", "y": 36},
            {"x": "Beryllium", "y": 79},
            {"x": "Vanadium", "y": 13},
            {"x": "Scandium", "y": 62},
            {"x": "Mangaan", "y": 48},
            {"x": "Lithium", "y": 37},
            {"x": "Aluminium", "y": 28},
            {"x": "Garmanium", "y": 81},
            {"x": "Silicium", "y": 93},
            {"x": "Tantalum", "y": 47},
            {"x": "Grafiet", "y": 63},
            {"x": "Veldsplaat", "y": 87},
            {"x": "Barieten", "y": 22},
            {"x": "Fluoriet", "y": 15},
            {"x": "Cokeskolen", "y": 50}
        ]
    },
    {
        "id": "Overige machines en gereedschapswerktuigen",
        "worth": 1860,
        "data": [
            {"x": "Dysprosium", "y": 45},
            {"x": "Neodymium", "y": 34},
            {"x": "Terbium", "y": 63},
            {"x": "Magnesium", "y": 22},
            {"x": "Niobrum", "y": 74},
            {"x": "Samarium", "y": 48},
            {"x": "Iridium", "y": 91},
            {"x": "Praseodymium", "y": 19},
            {"x": "Ruthenium", "y": 78},
            {"x": "Rhodium", "y": 29},
            {"x": "Cerium", "y": 37},
            {"x": "Kobalt", "y": 53},
            {"x": "Europium", "y": 60},
            {"x": "Ytterbium", "y": 17},
            {"x": "Strontium", "y": 94},
            {"x": "Fosfor", "y": 71},
            {"x": "Platina", "y": 38},
            {"x": "Gallium", "y": 55},
            {"x": "Boor", "y": 20},
            {"x": "Palladium", "y": 62},
            {"x": "Gadolinium", "y": 47},
            {"x": "Wolfraam", "y": 72},
            {"x": "Yttrium", "y": 8},
            {"x": "Lanthanum", "y": 25},
            {"x": "Anitmoon", "y": 81},
            {"x": "Beryllium", "y": 40},
            {"x": "Vanadium", "y": 14},
            {"x": "Scandium", "y": 52},
            {"x": "Mangaan", "y": 35},
            {"x": "Lithium", "y": 69},
            {"x": "Aluminium", "y": 21},
            {"x": "Garmanium", "y": 87},
            {"x": "Silicium", "y": 30},
            {"x": "Tantalum", "y": 90},
            {"x": "Grafiet", "y": 56},
            {"x": "Veldsplaat", "y": 64},
            {"x": "Barieten", "y": 42},
            {"x": "Fluoriet", "y": 73},
            {"x": "Cokeskolen", "y": 31}
        ]
    },
    {
        "id": "Producten van rubber of kunststof",
        "worth": 1750,
        "data": [
            {"x": "Dysprosium", "y": 23},
            {"x": "Neodymium", "y": 48},
            {"x": "Terbium", "y": 62},
            {"x": "Magnesium", "y": 31},
            {"x": "Niobrum", "y": 88},
            {"x": "Samarium", "y": 74},
            {"x": "Iridium", "y": 95},
            {"x": "Praseodymium", "y": 42},
            {"x": "Ruthenium", "y": 18},
            {"x": "Rhodium", "y": 58},
            {"x": "Cerium", "y": 26},
            {"x": "Kobalt", "y": 65},
            {"x": "Europium", "y": 53},
            {"x": "Ytterbium", "y": 37},
            {"x": "Strontium", "y": 70},
            {"x": "Fosfor", "y": 44},
            {"x": "Platina", "y": 21},
            {"x": "Gallium", "y": 60},
            {"x": "Boor", "y": 39},
            {"x": "Palladium", "y": 86},
            {"x": "Gadolinium", "y": 93},
            {"x": "Wolfraam", "y": 14},
            {"x": "Yttrium", "y": 47},
            {"x": "Lanthanum", "y": 29},
            {"x": "Anitmoon", "y": 56},
            {"x": "Beryllium", "y": 19},
            {"x": "Vanadium", "y": 66},
            {"x": "Scandium", "y": 22},
            {"x": "Mangaan", "y": 40},
            {"x": "Lithium", "y": 31},
            {"x": "Aluminium", "y": 72},
            {"x": "Garmanium", "y": 64},
            {"x": "Silicium", "y": 38},
            {"x": "Tantalum", "y": 93},
            {"x": "Grafiet", "y": 48},
            {"x": "Veldsplaat", "y": 85},
            {"x": "Barieten", "y": 25},
            {"x": "Fluoriet", "y": 17},
            {"x": "Cokeskolen", "y": 41}
        ]
    },
    {
        "id": "Ijzer en staal en halffabricaten daarvan (behalve buizen)",
        "worth": 1600,
        "data": [
            {"x": "Dysprosium", "y": 36},
            {"x": "Neodymium", "y": 59},
            {"x": "Terbium", "y": 12},
            {"x": "Magnesium", "y": 72},
            {"x": "Niobrum", "y": 47},
            {"x": "Samarium", "y": 83},
            {"x": "Iridium", "y": 6},
            {"x": "Praseodymium", "y": 25},
            {"x": "Ruthenium", "y": 91},
            {"x": "Rhodium", "y": 43},
            {"x": "Cerium", "y": 34},
            {"x": "Kobalt", "y": 52},
            {"x": "Europium", "y": 39},
            {"x": "Ytterbium", "y": 48},
            {"x": "Strontium", "y": 61},
            {"x": "Fosfor", "y": 30},
            {"x": "Platina", "y": 20},
            {"x": "Gallium", "y": 75},
            {"x": "Boor", "y": 19},
            {"x": "Palladium", "y": 89},
            {"x": "Gadolinium", "y": 62},
            {"x": "Wolfraam", "y": 27},
            {"x": "Yttrium", "y": 57},
            {"x": "Lanthanum", "y": 39},
            {"x": "Anitmoon", "y": 96},
            {"x": "Beryllium", "y": 44},
            {"x": "Vanadium", "y": 18},
            {"x": "Scandium", "y": 22},
            {"x": "Mangaan", "y": 60},
            {"x": "Lithium", "y": 71},
            {"x": "Aluminium", "y": 28},
            {"x": "Garmanium", "y": 36},
            {"x": "Silicium", "y": 40},
            {"x": "Tantalum", "y": 83},
            {"x": "Grafiet", "y": 12},
            {"x": "Veldsplaat", "y": 92},
            {"x": "Barieten", "y": 23},
            {"x": "Fluoriet", "y": 77},
            {"x": "Cokeskolen", "y": 54}
        ]
    },
    {
        "id": "Overig elektrische machines en apparaten",
        "worth": 1500,
        "data": [
            {"x": "Dysprosium", "y": 47},
            {"x": "Neodymium", "y": 30},
            {"x": "Terbium", "y": 64},
            {"x": "Magnesium", "y": 29},
            {"x": "Niobrum", "y": 78},
            {"x": "Samarium", "y": 56},
            {"x": "Iridium", "y": 96},
            {"x": "Praseodymium", "y": 18},
            {"x": "Ruthenium", "y": 80},
            {"x": "Rhodium", "y": 37},
            {"x": "Cerium", "y": 25},
            {"x": "Kobalt", "y": 45},
            {"x": "Europium", "y": 72},
            {"x": "Ytterbium", "y": 39},
            {"x": "Strontium", "y": 90},
            {"x": "Fosfor", "y": 50},
            {"x": "Platina", "y": 31},
            {"x": "Gallium", "y": 63},
            {"x": "Boor", "y": 28},
            {"x": "Palladium", "y": 85},
            {"x": "Gadolinium", "y": 41},
            {"x": "Wolfraam", "y": 32},
            {"x": "Yttrium", "y": 22},
            {"x": "Lanthanum", "y": 60},
            {"x": "Anitmoon", "y": 76},
            {"x": "Beryllium", "y": 43},
            {"x": "Vanadium", "y": 67},
            {"x": "Scandium", "y": 12},
            {"x": "Mangaan", "y": 35},
            {"x": "Lithium", "y": 57},
            {"x": "Aluminium", "y": 20},
            {"x": "Garmanium", "y": 68},
            {"x": "Silicium", "y": 46},
            {"x": "Tantalum", "y": 92},
            {"x": "Grafiet", "y": 34},
            {"x": "Veldsplaat", "y": 84},
            {"x": "Barieten", "y": 24},
            {"x": "Fluoriet", "y": 10},
            {"x": "Cokeskolen", "y": 41}
        ]
    },
    {
        "id": "Andere transportmiddelen",
        "worth": 1243,
        "data": [
            {"x": "Dysprosium", "y": 56},
            {"x": "Neodymium", "y": 38},
            {"x": "Terbium", "y": 29},
            {"x": "Magnesium", "y": 74},
            {"x": "Niobrum", "y": 22},
            {"x": "Samarium", "y": 61},
            {"x": "Iridium", "y": 89},
            {"x": "Praseodymium", "y": 14},
            {"x": "Ruthenium", "y": 48},
            {"x": "Rhodium", "y": 33},
            {"x": "Cerium", "y": 17},
            {"x": "Kobalt", "y": 62},
            {"x": "Europium", "y": 24},
            {"x": "Ytterbium", "y": 49},
            {"x": "Strontium", "y": 31},
            {"x": "Fosfor", "y": 54},
            {"x": "Platina", "y": 18},
            {"x": "Gallium", "y": 37},
            {"x": "Boor", "y": 80},
            {"x": "Palladium", "y": 93},
            {"x": "Gadolinium", "y": 64},
            {"x": "Wolfraam", "y": 25},
            {"x": "Yttrium", "y": 13},
            {"x": "Lanthanum", "y": 47},
            {"x": "Anitmoon", "y": 71},
            {"x": "Beryllium", "y": 36},
            {"x": "Vanadium", "y": 57},
            {"x": "Scandium", "y": 21},
            {"x": "Mangaan", "y": 43},
            {"x": "Lithium", "y": 62},
            {"x": "Aluminium", "y": 19},
            {"x": "Garmanium", "y": 58},
            {"x": "Silicium", "y": 46},
            {"x": "Tantalum", "y": 90},
            {"x": "Grafiet", "y": 12},
            {"x": "Veldsplaat", "y": 77},
            {"x": "Barieten", "y": 27},
            {"x": "Fluoriet", "y": 11},
            {"x": "Cokeskolen", "y": 41}
        ]
    },
    {
    "id": "Elektronische onderdelen en zend- en transmissietoestellen",
    "worth": 1100,
    "data": [
        {"x": "Dysprosium", "y": 41},
        {"x": "Neodymium", "y": 27},
        {"x": "Terbium", "y": 50},
        {"x": "Magnesium", "y": 16},
        {"x": "Niobrum", "y": 69},
        {"x": "Samarium", "y": 54},
        {"x": "Iridium", "y": 83},
        {"x": "Praseodymium", "y": 12},
        {"x": "Ruthenium", "y": 45},
        {"x": "Rhodium", "y": 30},
        {"x": "Cerium", "y": 29},
        {"x": "Kobalt", "y": 38},
        {"x": "Europium", "y": 64},
        {"x": "Ytterbium", "y": 22},
        {"x": "Strontium", "y": 71},
        {"x": "Fosfor", "y": 36},
        {"x": "Platina", "y": 19},
        {"x": "Gallium", "y": 57},
        {"x": "Boor", "y": 30},
        {"x": "Palladium", "y": 78},
        {"x": "Gadolinium", "y": 43},
        {"x": "Wolfraam", "y": 11},
        {"x": "Yttrium", "y": 35},
        {"x": "Lanthanum", "y": 49},
        {"x": "Anitmoon", "y": 66},
        {"x": "Beryllium", "y": 24},
        {"x": "Vanadium", "y": 31},
        {"x": "Scandium", "y": 18},
        {"x": "Mangaan", "y": 54},
        {"x": "Lithium", "y": 45},
        {"x": "Aluminium", "y": 12},
        {"x": "Garmanium", "y": 41},
        {"x": "Silicium", "y": 52},
        {"x": "Tantalum", "y": 77},
        {"x": "Grafiet", "y": 27},
        {"x": "Veldsplaat", "y": 61},
        {"x": "Barieten", "y": 20},
        {"x": "Fluoriet", "y": 15},
        {"x": "Cokeskolen", "y": 32}
    ]
},
    {
    "id": "Ketels, ijzerwaren, wapens en andere producten van metaal",
    "worth": 1050,
    "data": [
        {"x": "Dysprosium", "y": 30},
        {"x": "Neodymium", "y": 43},
        {"x": "Terbium", "y": 27},
        {"x": "Magnesium", "y": 65},
        {"x": "Niobrum", "y": 22},
        {"x": "Samarium", "y": 58},
        {"x": "Iridium", "y": 72},
        {"x": "Praseodymium", "y": 19},
        {"x": "Ruthenium", "y": 38},
        {"x": "Rhodium", "y": 48},
        {"x": "Cerium", "y": 32},
        {"x": "Kobalt", "y": 42},
        {"x": "Europium", "y": 21},
        {"x": "Ytterbium", "y": 36},
        {"x": "Strontium", "y": 64},
        {"x": "Fosfor", "y": 29},
        {"x": "Platina", "y": 18},
        {"x": "Gallium", "y": 46},
        {"x": "Boor", "y": 24},
        {"x": "Palladium", "y": 74},
        {"x": "Gadolinium", "y": 49},
        {"x": "Wolfraam", "y": 11},
        {"x": "Yttrium", "y": 33},
        {"x": "Lanthanum", "y": 44},
        {"x": "Anitmoon", "y": 58},
        {"x": "Beryllium", "y": 19},
        {"x": "Vanadium", "y": 40},
        {"x": "Scandium", "y": 21},
        {"x": "Mangaan", "y": 47},
        {"x": "Lithium", "y": 31},
        {"x": "Aluminium", "y": 25},
        {"x": "Garmanium", "y": 37},
        {"x": "Silicium", "y": 39},
        {"x": "Tantalum", "y": 60},
        {"x": "Grafiet", "y": 18},
        {"x": "Veldsplaat", "y": 70},
        {"x": "Barieten", "y": 14},
        {"x": "Fluoriet", "y": 20},
        {"x": "Cokeskolen", "y": 28}
    ]
},
    {
    "id": "Kantoormachines en computers",
    "worth": 1000,
    "data": [
        {"x": "Dysprosium", "y": 24},
        {"x": "Neodymium", "y": 36},
        {"x": "Terbium", "y": 51},
        {"x": "Magnesium", "y": 12},
        {"x": "Niobrum", "y": 45},
        {"x": "Samarium", "y": 56},
        {"x": "Iridium", "y": 89},
        {"x": "Praseodymium", "y": 21},
        {"x": "Ruthenium", "y": 66},
        {"x": "Rhodium", "y": 28},
        {"x": "Cerium", "y": 19},
        {"x": "Kobalt", "y": 39},
        {"x": "Europium", "y": 59},
        {"x": "Ytterbium", "y": 40},
        {"x": "Strontium", "y": 70},
        {"x": "Fosfor", "y": 33},
        {"x": "Platina", "y": 25},
        {"x": "Gallium", "y": 51},
        {"x": "Boor", "y": 19},
        {"x": "Palladium", "y": 73},
        {"x": "Gadolinium", "y": 60},
        {"x": "Wolfraam", "y": 13},
        {"x": "Yttrium", "y": 23},
        {"x": "Lanthanum", "y": 38},
        {"x": "Anitmoon", "y": 51},
        {"x": "Beryllium", "y": 17},
        {"x": "Vanadium", "y": 41},
        {"x": "Scandium", "y": 11},
        {"x": "Mangaan", "y": 57},
        {"x": "Lithium", "y": 34},
        {"x": "Aluminium", "y": 20},
        {"x": "Garmanium", "y": 42},
        {"x": "Silicium", "y": 44},
        {"x": "Tantalum", "y": 68},
        {"x": "Grafiet", "y": 22},
        {"x": "Veldsplaat", "y": 58},
        {"x": "Barieten", "y": 15},
        {"x": "Fluoriet", "y": 17},
        {"x": "Cokeskolen", "y": 23}
    ]
},
    {
    "id": "Kunststoffen en syntetische rubber in primaire vormen",
    "worth": 1000,
    "data": [
        {"x": "Dysprosium", "y": 40},
        {"x": "Neodymium", "y": 28},
        {"x": "Terbium", "y": 34},
        {"x": "Magnesium", "y": 58},
        {"x": "Niobrum", "y": 43},
        {"x": "Samarium", "y": 22},
        {"x": "Iridium", "y": 76},
        {"x": "Praseodymium", "y": 30},
        {"x": "Ruthenium", "y": 53},
        {"x": "Rhodium", "y": 39},
        {"x": "Cerium", "y": 16},
        {"x": "Kobalt", "y": 64},
        {"x": "Europium", "y": 47},
        {"x": "Ytterbium", "y": 33},
        {"x": "Strontium", "y": 61},
        {"x": "Fosfor", "y": 27},
        {"x": "Platina", "y": 18},
        {"x": "Gallium", "y": 44},
        {"x": "Boor", "y": 24},
        {"x": "Palladium", "y": 63},
        {"x": "Gadolinium", "y": 39},
        {"x": "Wolfraam", "y": 12},
        {"x": "Yttrium", "y": 25},
        {"x": "Lanthanum", "y": 56},
        {"x": "Anitmoon", "y": 41},
        {"x": "Beryllium", "y": 15},
        {"x": "Vanadium", "y": 27},
        {"x": "Scandium", "y": 13},
        {"x": "Mangaan", "y": 48},
        {"x": "Lithium", "y": 52},
        {"x": "Aluminium", "y": 31},
        {"x": "Garmanium", "y": 38},
        {"x": "Silicium", "y": 51},
        {"x": "Tantalum", "y": 74},
        {"x": "Grafiet", "y": 21},
        {"x": "Veldsplaat", "y": 49},
        {"x": "Barieten", "y": 19},
        {"x": "Fluoriet", "y": 29},
        {"x": "Cokeskolen", "y": 37}
    ]
},
    {
    "id": "Medische, precisie- en optische instrumenten",
    "worth": 900,
    "data": [
        {"x": "Dysprosium", "y": 56},
        {"x": "Neodymium", "y": 30},
        {"x": "Terbium", "y": 44},
        {"x": "Magnesium", "y": 24},
        {"x": "Niobrum", "y": 59},
        {"x": "Samarium", "y": 34},
        {"x": "Iridium", "y": 81},
        {"x": "Praseodymium", "y": 22},
        {"x": "Ruthenium", "y": 39},
        {"x": "Rhodium", "y": 50},
        {"x": "Cerium", "y": 18},
        {"x": "Kobalt", "y": 63},
        {"x": "Europium", "y": 45},
        {"x": "Ytterbium", "y": 26},
        {"x": "Strontium", "y": 67},
        {"x": "Fosfor", "y": 21},
        {"x": "Platina", "y": 32},
        {"x": "Gallium", "y": 39},
        {"x": "Boor", "y": 48},
        {"x": "Palladium", "y": 58},
        {"x": "Gadolinium", "y": 41},
        {"x": "Wolfraam", "y": 12},
        {"x": "Yttrium", "y": 27},
        {"x": "Lanthanum", "y": 52},
        {"x": "Anitmoon", "y": 44},
        {"x": "Beryllium", "y": 36},
        {"x": "Vanadium", "y": 22},
        {"x": "Scandium", "y": 19},
        {"x": "Mangaan", "y": 33},
        {"x": "Lithium", "y": 61},
        {"x": "Aluminium", "y": 25},
        {"x": "Garmanium", "y": 50},
        {"x": "Silicium", "y": 49},
        {"x": "Tantalum", "y": 68},
        {"x": "Grafiet", "y": 14},
        {"x": "Veldsplaat", "y": 55},
        {"x": "Barieten", "y": 17},
        {"x": "Fluoriet", "y": 23},
        {"x": "Cokeskolen", "y": 19}
    ]
},
    {
    "id": "Drukwerk en opgenomen media",
    "worth": 800,
    "data": [
        {"x": "Dysprosium", "y": 29},
        {"x": "Neodymium", "y": 40},
        {"x": "Terbium", "y": 33},
        {"x": "Magnesium", "y": 51},
        {"x": "Niobrum", "y": 24},
        {"x": "Samarium", "y": 38},
        {"x": "Iridium", "y": 60},
        {"x": "Praseodymium", "y": 18},
        {"x": "Ruthenium", "y": 52},
        {"x": "Rhodium", "y": 41},
        {"x": "Cerium", "y": 19},
        {"x": "Kobalt", "y": 31},
        {"x": "Europium", "y": 21},
        {"x": "Ytterbium", "y": 23},
        {"x": "Strontium", "y": 56},
        {"x": "Fosfor", "y": 14},
        {"x": "Platina", "y": 26},
        {"x": "Gallium", "y": 39},
        {"x": "Boor", "y": 47},
        {"x": "Palladium", "y": 64},
        {"x": "Gadolinium", "y": 37},
        {"x": "Wolfraam", "y": 11},
        {"x": "Yttrium", "y": 22},
        {"x": "Lanthanum", "y": 55},
        {"x": "Anitmoon", "y": 31},
        {"x": "Beryllium", "y": 18},
        {"x": "Vanadium", "y": 44},
        {"x": "Scandium", "y": 20},
        {"x": "Mangaan", "y": 42},
        {"x": "Lithium", "y": 51},
        {"x": "Aluminium", "y": 15},
        {"x": "Garmanium", "y": 38},
        {"x": "Silicium", "y": 46},
        {"x": "Tantalum", "y": 69},
        {"x": "Grafiet", "y": 23},
        {"x": "Veldsplaat", "y": 41},
        {"x": "Barieten", "y": 12},
        {"x": "Fluoriet", "y": 17},
        {"x": "Cokeskolen", "y": 28}
    ]
},
    {
    "id": "Non-ferrometalen en producten daarvan",
    "worth": 700,
    "data": [
        {"x": "Dysprosium", "y": 25},
        {"x": "Neodymium", "y": 34},
        {"x": "Terbium", "y": 29},
        {"x": "Magnesium", "y": 50},
        {"x": "Niobrum", "y": 19},
        {"x": "Samarium", "y": 42},
        {"x": "Iridium", "y": 62},
        {"x": "Praseodymium", "y": 13},
        {"x": "Ruthenium", "y": 49},
        {"x": "Rhodium", "y": 37},
        {"x": "Cerium", "y": 22},
        {"x": "Kobalt", "y": 40},
        {"x": "Europium", "y": 17},
        {"x": "Ytterbium", "y": 28},
        {"x": "Strontium", "y": 53},
        {"x": "Fosfor", "y": 15},
        {"x": "Platina", "y": 20},
        {"x": "Gallium", "y": 44},
        {"x": "Boor", "y": 35},
        {"x": "Palladium", "y": 59},
        {"x": "Gadolinium", "y": 36},
        {"x": "Wolfraam", "y": 9},
        {"x": "Yttrium", "y": 24},
        {"x": "Lanthanum", "y": 50},
        {"x": "Anitmoon", "y": 40},
        {"x": "Beryllium", "y": 16},
        {"x": "Vanadium", "y": 30},
        {"x": "Scandium", "y": 18},
        {"x": "Mangaan", "y": 41},
        {"x": "Lithium", "y": 38},
        {"x": "Aluminium", "y": 21},
        {"x": "Garmanium", "y": 33},
        {"x": "Silicium", "y": 45},
        {"x": "Tantalum", "y": 65},
        {"x": "Grafiet", "y": 20},
        {"x": "Veldsplaat", "y": 47},
        {"x": "Barieten", "y": 14},
        {"x": "Fluoriet", "y": 12},
        {"x": "Cokeskolen", "y": 22}
    ]
},
    {
    "id": "Hout en kurkwaren (m.u.v. meubelen)",
    "worth": 650,
    "data": [
        {"x": "Dysprosium", "y": 31},
        {"x": "Neodymium", "y": 24},
        {"x": "Terbium", "y": 39},
        {"x": "Magnesium", "y": 58},
        {"x": "Niobrum", "y": 17},
        {"x": "Samarium", "y": 33},
        {"x": "Iridium", "y": 46},
        {"x": "Praseodymium", "y": 15},
        {"x": "Ruthenium", "y": 51},
        {"x": "Rhodium", "y": 41},
        {"x": "Cerium", "y": 19},
        {"x": "Kobalt", "y": 29},
        {"x": "Europium", "y": 20},
        {"x": "Ytterbium", "y": 26},
        {"x": "Strontium", "y": 42},
        {"x": "Fosfor", "y": 18},
        {"x": "Platina", "y": 29},
        {"x": "Gallium", "y": 38},
        {"x": "Boor", "y": 23},
        {"x": "Palladium", "y": 55},
        {"x": "Gadolinium", "y": 30},
        {"x": "Wolfraam", "y": 8},
        {"x": "Yttrium", "y": 22},
        {"x": "Lanthanum", "y": 47},
        {"x": "Anitmoon", "y": 34},
        {"x": "Beryllium", "y": 12},
        {"x": "Vanadium", "y": 26},
        {"x": "Scandium", "y": 14},
        {"x": "Mangaan", "y": 38},
        {"x": "Lithium", "y": 30},
        {"x": "Aluminium", "y": 22},
        {"x": "Garmanium", "y": 28},
        {"x": "Silicium", "y": 36},
        {"x": "Tantalum", "y": 62},
        {"x": "Grafiet", "y": 16},
        {"x": "Veldsplaat", "y": 44},
        {"x": "Barieten", "y": 11},
        {"x": "Fluoriet", "y": 13},
        {"x": "Cokeskolen", "y": 21}
    ]
},
    {
    "id": "Textiel",
    "worth": 600,
    "data": [
        {"x": "Dysprosium", "y": 21},
        {"x": "Neodymium", "y": 37},
        {"x": "Terbium", "y": 29},
        {"x": "Magnesium", "y": 52},
        {"x": "Niobrum", "y": 16},
        {"x": "Samarium", "y": 27},
        {"x": "Iridium", "y": 49},
        {"x": "Praseodymium", "y": 14},
        {"x": "Ruthenium", "y": 41},
        {"x": "Rhodium", "y": 32},
        {"x": "Cerium", "y": 18},
        {"x": "Kobalt", "y": 28},
        {"x": "Europium", "y": 22},
        {"x": "Ytterbium", "y": 25},
        {"x": "Strontium", "y": 47},
        {"x": "Fosfor", "y": 12},
        {"x": "Platina", "y": 23},
        {"x": "Gallium", "y": 34},
        {"x": "Boor", "y": 21},
        {"x": "Palladium", "y": 53},
        {"x": "Gadolinium", "y": 26},
        {"x": "Wolfraam", "y": 10},
        {"x": "Yttrium", "y": 20},
        {"x": "Lanthanum", "y": 42},
        {"x": "Anitmoon", "y": 31},
        {"x": "Beryllium", "y": 14},
        {"x": "Vanadium", "y": 28},
        {"x": "Scandium", "y": 15},
        {"x": "Mangaan", "y": 36},
        {"x": "Lithium", "y": 27},
        {"x": "Aluminium", "y": 20},
        {"x": "Garmanium", "y": 24},
        {"x": "Silicium", "y": 34},
        {"x": "Tantalum", "y": 60},
        {"x": "Grafiet", "y": 18},
        {"x": "Veldsplaat", "y": 40},
        {"x": "Barieten", "y": 9},
        {"x": "Fluoriet", "y": 12},
        {"x": "Cokeskolen", "y": 20}
    ]
},
    {
    "id": "Meubilair",
    "worth": 500,
    "data": [
        {"x": "Dysprosium", "y": 18},
        {"x": "Neodymium", "y": 29},
        {"x": "Terbium", "y": 24},
        {"x": "Magnesium", "y": 41},
        {"x": "Niobrum", "y": 13},
        {"x": "Samarium", "y": 22},
        {"x": "Iridium", "y": 39},
        {"x": "Praseodymium", "y": 12},
        {"x": "Ruthenium", "y": 34},
        {"x": "Rhodium", "y": 27},
        {"x": "Cerium", "y": 14},
        {"x": "Kobalt", "y": 24},
        {"x": "Europium", "y": 19},
        {"x": "Ytterbium", "y": 21},
        {"x": "Strontium", "y": 40},
        {"x": "Fosfor", "y": 10},
        {"x": "Platina", "y": 18},
        {"x": "Gallium", "y": 30},
        {"x": "Boor", "y": 17},
        {"x": "Palladium", "y": 46},
        {"x": "Gadolinium", "y": 23},
        {"x": "Wolfraam", "y": 8},
        {"x": "Yttrium", "y": 18},
        {"x": "Lanthanum", "y": 37},
        {"x": "Anitmoon", "y": 27},
        {"x": "Beryllium", "y": 11},
        {"x": "Vanadium", "y": 22},
        {"x": "Scandium", "y": 13},
        {"x": "Mangaan", "y": 30},
        {"x": "Lithium", "y": 25},
        {"x": "Aluminium", "y": 19},
        {"x": "Garmanium", "y": 21},
        {"x": "Silicium", "y": 29},
        {"x": "Tantalum", "y": 53},
        {"x": "Grafiet", "y": 16},
        {"x": "Veldsplaat", "y": 34},
        {"x": "Barieten", "y": 7},
        {"x": "Fluoriet", "y": 9},
        {"x": "Cokeskolen", "y": 17}
    ]
},
    {
    "id": "Huishoudapparaten (witgoed)",
    "worth": 300,
    "data": [
        {"x": "Dysprosium", "y": 13},
        {"x": "Neodymium", "y": 22},
        {"x": "Terbium", "y": 18},
        {"x": "Magnesium", "y": 29},
        {"x": "Niobrum", "y": 8},
        {"x": "Samarium", "y": 15},
        {"x": "Iridium", "y": 24},
        {"x": "Praseodymium", "y": 7},
        {"x": "Ruthenium", "y": 21},
        {"x": "Rhodium", "y": 17},
        {"x": "Cerium", "y": 9},
        {"x": "Kobalt", "y": 15},
        {"x": "Europium", "y": 11},
        {"x": "Ytterbium", "y": 13},
        {"x": "Strontium", "y": 26},
        {"x": "Fosfor", "y": 6},
        {"x": "Platina", "y": 12},
        {"x": "Gallium", "y": 19},
        {"x": "Boor", "y": 10},
        {"x": "Palladium", "y": 28},
        {"x": "Gadolinium", "y": 14},
        {"x": "Wolfraam", "y": 5},
        {"x": "Yttrium", "y": 11},
        {"x": "Lanthanum", "y": 24},
        {"x": "Anitmoon", "y": 17},
        {"x": "Beryllium", "y": 6},
        {"x": "Vanadium", "y": 13},
        {"x": "Scandium", "y": 8},
        {"x": "Mangaan", "y": 18},
        {"x": "Lithium", "y": 14},
        {"x": "Aluminium", "y": 10},
        {"x": "Garmanium", "y": 12},
        {"x": "Silicium", "y": 16},
        {"x": "Tantalum", "y": 29},
        {"x": "Grafiet", "y": 8},
        {"x": "Veldsplaat", "y": 18},
        {"x": "Barieten", "y": 4},
        {"x": "Fluoriet", "y": 6},
        {"x": "Cokeskolen", "y": 10}
    ]
},
    {
    "id": "Metalen constructieproducten",
    "worth": 200,
    "data": [
        {"x": "Dysprosium", "y": 9},
        {"x": "Neodymium", "y": 14},
        {"x": "Terbium", "y": 12},
        {"x": "Magnesium", "y": 20},
        {"x": "Niobrum", "y": 5},
        {"x": "Samarium", "y": 11},
        {"x": "Iridium", "y": 17},
        {"x": "Praseodymium", "y": 4},
        {"x": "Ruthenium", "y": 15},
        {"x": "Rhodium", "y": 12},
        {"x": "Cerium", "y": 6},
        {"x": "Kobalt", "y": 11},
        {"x": "Europium", "y": 8},
        {"x": "Ytterbium", "y": 9},
        {"x": "Strontium", "y": 19},
        {"x": "Fosfor", "y": 4},
        {"x": "Platina", "y": 7},
        {"x": "Gallium", "y": 12},
        {"x": "Boor", "y": 6},
        {"x": "Palladium", "y": 16},
        {"x": "Gadolinium", "y": 9},
        {"x": "Wolfraam", "y": 3},
        {"x": "Yttrium", "y": 7},
        {"x": "Lanthanum", "y": 16},
        {"x": "Anitmoon", "y": 12},
        {"x": "Beryllium", "y": 5},
        {"x": "Vanadium", "y": 10},
        {"x": "Scandium", "y": 6},
        {"x": "Mangaan", "y": 13},
        {"x": "Lithium", "y": 10},
        {"x": "Aluminium", "y": 7},
        {"x": "Garmanium", "y": 9},
        {"x": "Silicium", "y": 12},
        {"x": "Tantalum", "y": 21},
        {"x": "Grafiet", "y": 6},
        {"x": "Veldsplaat", "y": 13},
        {"x": "Barieten", "y": 3},
        {"x": "Fluoriet", "y": 4},
        {"x": "Cokeskolen", "y": 6}
    ]
},
    {
    "id": "Machines en werktuigen voor land en bosbouw",
    "worth": 190,
    "data": [
        {"x": "Dysprosium", "y": 8},
        {"x": "Neodymium", "y": 13},
        {"x": "Terbium", "y": 10},
        {"x": "Magnesium", "y": 16},
        {"x": "Niobrum", "y": 4},
        {"x": "Samarium", "y": 9},
        {"x": "Iridium", "y": 14},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 11},
        {"x": "Rhodium", "y": 9},
        {"x": "Cerium", "y": 5},
        {"x": "Kobalt", "y": 9},
        {"x": "Europium", "y": 6},
        {"x": "Ytterbium", "y": 8},
        {"x": "Strontium", "y": 17},
        {"x": "Fosfor", "y": 3},
        {"x": "Platina", "y": 6},
        {"x": "Gallium", "y": 10},
        {"x": "Boor", "y": 5},
        {"x": "Palladium", "y": 13},
        {"x": "Gadolinium", "y": 7},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 6},
        {"x": "Lanthanum", "y": 14},
        {"x": "Anitmoon", "y": 10},
        {"x": "Beryllium", "y": 4},
        {"x": "Vanadium", "y": 8},
        {"x": "Scandium", "y": 5},
        {"x": "Mangaan", "y": 11},
        {"x": "Lithium", "y": 9},
        {"x": "Aluminium", "y": 6},
        {"x": "Garmanium", "y": 8},
        {"x": "Silicium", "y": 10},
        {"x": "Tantalum", "y": 18},
        {"x": "Grafiet", "y": 5},
        {"x": "Veldsplaat", "y": 11},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 5}
    ]
},
    {
    "id": "Betonwaren en overige bouwmaterialen en bouwproducten",
    "worth": 187,
    "data": [
        {"x": "Dysprosium", "y": 7},
        {"x": "Neodymium", "y": 12},
        {"x": "Terbium", "y": 9},
        {"x": "Magnesium", "y": 15},
        {"x": "Niobrum", "y": 4},
        {"x": "Samarium", "y": 8},
        {"x": "Iridium", "y": 13},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 10},
        {"x": "Rhodium", "y": 8},
        {"x": "Cerium", "y": 5},
        {"x": "Kobalt", "y": 8},
        {"x": "Europium", "y": 6},
        {"x": "Ytterbium", "y": 7},
        {"x": "Strontium", "y": 16},
        {"x": "Fosfor", "y": 3},
        {"x": "Platina", "y": 5},
        {"x": "Gallium", "y": 9},
        {"x": "Boor", "y": 4},
        {"x": "Palladium", "y": 12},
        {"x": "Gadolinium", "y": 6},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 5},
        {"x": "Lanthanum", "y": 12},
        {"x": "Anitmoon", "y": 9},
        {"x": "Beryllium", "y": 4},
        {"x": "Vanadium", "y": 7},
        {"x": "Scandium", "y": 4},
        {"x": "Mangaan", "y": 10},
        {"x": "Lithium", "y": 8},
        {"x": "Aluminium", "y": 6},
        {"x": "Garmanium", "y": 7},
        {"x": "Silicium", "y": 9},
        {"x": "Tantalum", "y": 17},
        {"x": "Grafiet", "y": 4},
        {"x": "Veldsplaat", "y": 10},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Glas en glaswerk, keramische producten",
    "worth": 175,
    "data": [
        {"x": "Dysprosium", "y": 6},
        {"x": "Neodymium", "y": 11},
        {"x": "Terbium", "y": 8},
        {"x": "Magnesium", "y": 14},
        {"x": "Niobrum", "y": 3},
        {"x": "Samarium", "y": 7},
        {"x": "Iridium", "y": 11},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 9},
        {"x": "Rhodium", "y": 7},
        {"x": "Cerium", "y": 5},
        {"x": "Kobalt", "y": 7},
        {"x": "Europium", "y": 5},
        {"x": "Ytterbium", "y": 6},
        {"x": "Strontium", "y": 13},
        {"x": "Fosfor", "y": 3},
        {"x": "Platina", "y": 4},
        {"x": "Gallium", "y": 8},
        {"x": "Boor", "y": 4},
        {"x": "Palladium", "y": 10},
        {"x": "Gadolinium", "y": 5},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 4},
        {"x": "Lanthanum", "y": 10},
        {"x": "Anitmoon", "y": 8},
        {"x": "Beryllium", "y": 3},
        {"x": "Vanadium", "y": 6},
        {"x": "Scandium", "y": 3},
        {"x": "Mangaan", "y": 8},
        {"x": "Lithium", "y": 7},
        {"x": "Aluminium", "y": 5},
        {"x": "Garmanium", "y": 6},
        {"x": "Silicium", "y": 8},
        {"x": "Tantalum", "y": 14},
        {"x": "Grafiet", "y": 4},
        {"x": "Veldsplaat", "y": 9},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Televisie- en radiotoestellen, audio- en videoapparatuur (bruingoed)",
    "worth": 170,
    "data": [
        {"x": "Dysprosium", "y": 5},
        {"x": "Neodymium", "y": 9},
        {"x": "Terbium", "y": 7},
        {"x": "Magnesium", "y": 13},
        {"x": "Niobrum", "y": 3},
        {"x": "Samarium", "y": 6},
        {"x": "Iridium", "y": 10},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 8},
        {"x": "Rhodium", "y": 6},
        {"x": "Cerium", "y": 4},
        {"x": "Kobalt", "y": 6},
        {"x": "Europium", "y": 4},
        {"x": "Ytterbium", "y": 5},
        {"x": "Strontium", "y": 12},
        {"x": "Fosfor", "y": 3},
        {"x": "Platina", "y": 4},
        {"x": "Gallium", "y": 7},
        {"x": "Boor", "y": 4},
        {"x": "Palladium", "y": 9},
        {"x": "Gadolinium", "y": 4},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 4},
        {"x": "Lanthanum", "y": 9},
        {"x": "Anitmoon", "y": 7},
        {"x": "Beryllium", "y": 3},
        {"x": "Vanadium", "y": 5},
        {"x": "Scandium", "y": 3},
        {"x": "Mangaan", "y": 7},
        {"x": "Lithium", "y": 6},
        {"x": "Aluminium", "y": 4},
        {"x": "Garmanium", "y": 5},
        {"x": "Silicium", "y": 7},
        {"x": "Tantalum", "y": 12},
        {"x": "Grafiet", "y": 4},
        {"x": "Veldsplaat", "y": 8},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Cement, kalk en glas",
    "worth": 165,
    "data": [
        {"x": "Dysprosium", "y": 5},
        {"x": "Neodymium", "y": 9},
        {"x": "Terbium", "y": 7},
        {"x": "Magnesium", "y": 12},
        {"x": "Niobrum", "y": 3},
        {"x": "Samarium", "y": 6},
        {"x": "Iridium", "y": 9},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 7},
        {"x": "Rhodium", "y": 6},
        {"x": "Cerium", "y": 4},
        {"x": "Kobalt", "y": 6},
        {"x": "Europium", "y": 4},
        {"x": "Ytterbium", "y": 5},
        {"x": "Strontium", "y": 11},
        {"x": "Fosfor", "y": 3},
        {"x": "Platina", "y": 4},
        {"x": "Gallium", "y": 6},
        {"x": "Boor", "y": 4},
        {"x": "Palladium", "y": 8},
        {"x": "Gadolinium", "y": 4},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 4},
        {"x": "Lanthanum", "y": 8},
        {"x": "Anitmoon", "y": 6},
        {"x": "Beryllium", "y": 3},
        {"x": "Vanadium", "y": 5},
        {"x": "Scandium", "y": 3},
        {"x": "Mangaan", "y": 7},
        {"x": "Lithium", "y": 6},
        {"x": "Aluminium", "y": 4},
        {"x": "Garmanium", "y": 5},
        {"x": "Silicium", "y": 7},
        {"x": "Tantalum", "y": 11},
        {"x": "Grafiet", "y": 4},
        {"x": "Veldsplaat", "y": 7},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Kunstmeststoffen en stikstofverbindingen (behalve natuurlijke meststoffen)",
    "worth": 160,
    "data": [
        {"x": "Dysprosium", "y": 5},
        {"x": "Neodymium", "y": 8},
        {"x": "Terbium", "y": 7},
        {"x": "Magnesium", "y": 12},
        {"x": "Niobrum", "y": 3},
        {"x": "Samarium", "y": 6},
        {"x": "Iridium", "y": 9},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 7},
        {"x": "Rhodium", "y": 5},
        {"x": "Cerium", "y": 4},
        {"x": "Kobalt", "y": 5},
        {"x": "Europium", "y": 4},
        {"x": "Ytterbium", "y": 5},
        {"x": "Strontium", "y": 10},
        {"x": "Fosfor", "y": 3},
        {"x": "Platina", "y": 4},
        {"x": "Gallium", "y": 6},
        {"x": "Boor", "y": 3},
        {"x": "Palladium", "y": 8},
        {"x": "Gadolinium", "y": 4},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 4},
        {"x": "Lanthanum", "y": 8},
        {"x": "Anitmoon", "y": 6},
        {"x": "Beryllium", "y": 3},
        {"x": "Vanadium", "y": 5},
        {"x": "Scandium", "y": 3},
        {"x": "Mangaan", "y": 7},
        {"x": "Lithium", "y": 6},
        {"x": "Aluminium", "y": 4},
        {"x": "Garmanium", "y": 5},
        {"x": "Silicium", "y": 7},
        {"x": "Tantalum", "y": 10},
        {"x": "Grafiet", "y": 4},
        {"x": "Veldsplaat", "y": 7},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Steenkool en bruinkool",
    "worth": 150,
    "data": [
        {"x": "Dysprosium", "y": 5},
        {"x": "Neodymium", "y": 8},
        {"x": "Terbium", "y": 6},
        {"x": "Magnesium", "y": 11},
        {"x": "Niobrum", "y": 3},
        {"x": "Samarium", "y": 5},
        {"x": "Iridium", "y": 8},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 6},
        {"x": "Rhodium", "y": 5},
        {"x": "Cerium", "y": 3},
        {"x": "Kobalt", "y": 5},
        {"x": "Europium", "y": 3},
        {"x": "Ytterbium", "y": 4},
        {"x": "Strontium", "y": 9},
        {"x": "Fosfor", "y": 2},
        {"x": "Platina", "y": 3},
        {"x": "Gallium", "y": 5},
        {"x": "Boor", "y": 3},
        {"x": "Palladium", "y": 7},
        {"x": "Gadolinium", "y": 3},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 3},
        {"x": "Lanthanum", "y": 7},
        {"x": "Anitmoon", "y": 5},
        {"x": "Beryllium", "y": 2},
        {"x": "Vanadium", "y": 4},
        {"x": "Scandium", "y": 3},
        {"x": "Mangaan", "y": 6},
        {"x": "Lithium", "y": 5},
        {"x": "Aluminium", "y": 3},
        {"x": "Garmanium", "y": 4},
        {"x": "Silicium", "y": 6},
        {"x": "Tantalum", "y": 9},
        {"x": "Grafiet", "y": 3},
        {"x": "Veldsplaat", "y": 6},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Steen, zand, grind, klei, turf en andere delfstoffen",
    "worth": 120,
    "data": [
        {"x": "Dysprosium", "y": 4},
        {"x": "Neodymium", "y": 7},
        {"x": "Terbium", "y": 5},
        {"x": "Magnesium", "y": 9},
        {"x": "Niobrum", "y": 3},
        {"x": "Samarium", "y": 5},
        {"x": "Iridium", "y": 7},
        {"x": "Praseodymium", "y": 3},
        {"x": "Ruthenium", "y": 5},
        {"x": "Rhodium", "y": 4},
        {"x": "Cerium", "y": 3},
        {"x": "Kobalt", "y": 4},
        {"x": "Europium", "y": 3},
        {"x": "Ytterbium", "y": 4},
        {"x": "Strontium", "y": 8},
        {"x": "Fosfor", "y": 2},
        {"x": "Platina", "y": 3},
        {"x": "Gallium", "y": 4},
        {"x": "Boor", "y": 3},
        {"x": "Palladium", "y": 6},
        {"x": "Gadolinium", "y": 3},
        {"x": "Wolfraam", "y": 2},
        {"x": "Yttrium", "y": 3},
        {"x": "Lanthanum", "y": 6},
        {"x": "Anitmoon", "y": 5},
        {"x": "Beryllium", "y": 2},
        {"x": "Vanadium", "y": 4},
        {"x": "Scandium", "y": 3},
        {"x": "Mangaan", "y": 5},
        {"x": "Lithium", "y": 4},
        {"x": "Aluminium", "y": 3},
        {"x": "Garmanium", "y": 4},
        {"x": "Silicium", "y": 5},
        {"x": "Tantalum", "y": 8},
        {"x": "Grafiet", "y": 3},
        {"x": "Veldsplaat", "y": 5},
        {"x": "Barieten", "y": 2},
        {"x": "Fluoriet", "y": 3},
        {"x": "Cokeskolen", "y": 4}
    ]
},
    {
    "id": "Buizen, pijpen en holle profielen van ijzer en staal",
    "worth": 110,
    "data": [
        {"x": "Dysprosium", "y": 3},
        {"x": "Neodymium", "y": 6},
        {"x": "Terbium", "y": 5},
        {"x": "Magnesium", "y": 8},
        {"x": "Niobrum", "y": 2},
        {"x": "Samarium", "y": 4},
        {"x": "Iridium", "y": 6},
        {"x": "Praseodymium", "y": 2},
        {"x": "Ruthenium", "y": 4},
        {"x": "Rhodium", "y": 3},
        {"x": "Cerium", "y": 2},
        {"x": "Kobalt", "y": 3},
        {"x": "Europium", "y": 2},
        {"x": "Ytterbium", "y": 3},
        {"x": "Strontium", "y": 7},
        {"x": "Fosfor", "y": 2},
        {"x": "Platina", "y": 2},
        {"x": "Gallium", "y": 4},
        {"x": "Boor", "y": 2},
        {"x": "Palladium", "y": 5},
        {"x": "Gadolinium", "y": 2},
        {"x": "Wolfraam", "y": 1},
        {"x": "Yttrium", "y": 2},
        {"x": "Lanthanum", "y": 5},
        {"x": "Anitmoon", "y": 4},
        {"x": "Beryllium", "y": 2},
        {"x": "Vanadium", "y": 3},
        {"x": "Scandium", "y": 2},
        {"x": "Mangaan", "y": 4},
        {"x": "Lithium", "y": 3},
        {"x": "Aluminium", "y": 2},
        {"x": "Garmanium", "y": 3},
        {"x": "Silicium", "y": 4},
        {"x": "Tantalum", "y": 7},
        {"x": "Grafiet", "y": 2},
        {"x": "Veldsplaat", "y": 4},
        {"x": "Barieten", "y": 1},
        {"x": "Fluoriet", "y": 2},
        {"x": "Cokeskolen", "y": 3}
    ]
},
    {
    "id": "Mineralen voor de chemische en kunstmest industrie",
    "worth": 110,
    "data": [
        {"x": "Dysprosium", "y": 3},
        {"x": "Neodymium", "y": 6},
        {"x": "Terbium", "y": 5},
        {"x": "Magnesium", "y": 7},
        {"x": "Niobrum", "y": 2},
        {"x": "Samarium", "y": 4},
        {"x": "Iridium", "y": 6},
        {"x": "Praseodymium", "y": 2},
        {"x": "Ruthenium", "y": 4},
        {"x": "Rhodium", "y": 3},
        {"x": "Cerium", "y": 2},
        {"x": "Kobalt", "y": 3},
        {"x": "Europium", "y": 2},
        {"x": "Ytterbium", "y": 3},
        {"x": "Strontium", "y": 7},
        {"x": "Fosfor", "y": 2},
        {"x": "Platina", "y": 2},
        {"x": "Gallium", "y": 4},
        {"x": "Boor", "y": 2},
        {"x": "Palladium", "y": 5},
        {"x": "Gadolinium", "y": 2},
        {"x": "Wolfraam", "y": 1},
        {"x": "Yttrium", "y": 2},
        {"x": "Lanthanum", "y": 5},
        {"x": "Anitmoon", "y": 4},
        {"x": "Beryllium", "y": 2},
        {"x": "Vanadium", "y": 3},
        {"x": "Scandium", "y": 2},
        {"x": "Mangaan", "y": 4},
        {"x": "Lithium", "y": 3},
        {"x": "Aluminium", "y": 2},
        {"x": "Garmanium", "y": 3},
        {"x": "Silicium", "y": 4},
        {"x": "Tantalum", "y": 7},
        {"x": "Grafiet", "y": 2},
        {"x": "Veldsplaat", "y": 4},
        {"x": "Barieten", "y": 1},
        {"x": "Fluoriet", "y": 2},
        {"x": "Cokeskolen", "y": 3}
    ]
},
    {
    "id": "Non-ferrometaalertsen",
    "worth": 105,
    "data": [
        {"x": "Dysprosium", "y": 3},
        {"x": "Neodymium", "y": 5},
        {"x": "Terbium", "y": 4},
        {"x": "Magnesium", "y": 6},
        {"x": "Niobrum", "y": 2},
        {"x": "Samarium", "y": 4},
        {"x": "Iridium", "y": 5},
        {"x": "Praseodymium", "y": 2},
        {"x": "Ruthenium", "y": 4},
        {"x": "Rhodium", "y": 3},
        {"x": "Cerium", "y": 2},
        {"x": "Kobalt", "y": 3},
        {"x": "Europium", "y": 2},
        {"x": "Ytterbium", "y": 3},
        {"x": "Strontium", "y": 6},
        {"x": "Fosfor", "y": 2},
        {"x": "Platina", "y": 2},
        {"x": "Gallium", "y": 3},
        {"x": "Boor", "y": 2},
        {"x": "Palladium", "y": 4},
        {"x": "Gadolinium", "y": 2},
        {"x": "Wolfraam", "y": 1},
        {"x": "Yttrium", "y": 2},
        {"x": "Lanthanum", "y": 4},
        {"x": "Anitmoon", "y": 3},
        {"x": "Beryllium", "y": 2},
        {"x": "Vanadium", "y": 3},
        {"x": "Scandium", "y": 2},
        {"x": "Mangaan", "y": 4},
        {"x": "Lithium", "y": 3},
        {"x": "Aluminium", "y": 2},
        {"x": "Garmanium", "y": 3},
        {"x": "Silicium", "y": 4},
        {"x": "Tantalum", "y": 6},
        {"x": "Grafiet", "y": 2},
        {"x": "Veldsplaat", "y": 4},
        {"x": "Barieten", "y": 1},
        {"x": "Fluoriet", "y": 2},
        {"x": "Cokeskolen", "y": 3}
    ]
},
    {
    "id": "Zout",
    "worth": 100,
    "data": [
        {"x": "Dysprosium", "y": 2},
        {"x": "Neodymium", "y": 4},
        {"x": "Terbium", "y": 3},
        {"x": "Magnesium", "y": 5},
        {"x": "Niobrum", "y": 1},
        {"x": "Samarium", "y": 3},
        {"x": "Iridium", "y": 4},
        {"x": "Praseodymium", "y": 1},
        {"x": "Ruthenium", "y": 3},
        {"x": "Rhodium", "y": 2},
        {"x": "Cerium", "y": 1},
        {"x": "Kobalt", "y": 2},
        {"x": "Europium", "y": 1},
        {"x": "Ytterbium", "y": 2},
        {"x": "Strontium", "y": 5},
        {"x": "Fosfor", "y": 1},
        {"x": "Platina", "y": 1},
        {"x": "Gallium", "y": 2},
        {"x": "Boor", "y": 1},
        {"x": "Palladium", "y": 3},
        {"x": "Gadolinium", "y": 1},
        {"x": "Wolfraam", "y": 1},
        {"x": "Yttrium", "y": 1},
        {"x": "Lanthanum", "y": 3},
        {"x": "Anitmoon", "y": 2},
        {"x": "Beryllium", "y": 1},
        {"x": "Vanadium", "y": 2},
        {"x": "Scandium", "y": 1},
        {"x": "Mangaan", "y": 3},
        {"x": "Lithium", "y": 2},
        {"x": "Aluminium", "y": 1},
        {"x": "Garmanium", "y": 2},
        {"x": "Silicium", "y": 3},
        {"x": "Tantalum", "y": 5},
        {"x": "Grafiet", "y": 1},
        {"x": "Veldsplaat", "y": 3},
        {"x": "Barieten", "y": 1},
        {"x": "Fluoriet", "y": 1},
        {"x": "Cokeskolen", "y": 2}
    ]
}
]